packages:
  - "git-modules/mono/typescript/packages/events"
  - "git-modules/mono/typescript/packages/counter"
  - "git-modules/mono/typescript/packages/utils"
  - "packages/model"
  - "packages/query"
  - "packages/hybrid-logical-clock"
  - "packages/website"
  - "examples/todo-app"
